### ISSUE TITLE
Sanitize all content to prevent js injection attacks.

### ISSUE THREAD

**Issue by ethanpailes** [Frames-Proj/frames#70]
I have not tested it, but I bet someone could put a <script> tag in a video description or a comment body and cause havoc with the app. We should prevent them from doing that.

**Comment by GrahamGoudeau** [comment]
Video titles/descriptions are not vulnerable, but testing revealed another issue: #89 
I haven't tested comments yet

**Comment by GrahamGoudeau** [comment]
#89

**Comment by ethanpailes** [comment]
Done
